services:
  autodelete:
    image: ghcr.io/ksurl/autodelete-discord
    container_name: autodelete
    ports:
      - 2202:2202
    volumes:
      - ./config.yml:/app/config.yml
      - ./data:/app/data
    restart: always
