version: "3.8"
services:
  autodelete:
    image: ghcr.io/ksurl/autodelete-discord
    container_name: autodelete
    ports:
      - 2202:2202
    volumes:
      - <HOST>/config.yml:/app/config.yml
      - <volume>:/app/data
    restart: always
