#!/bin/sh

if [ ! -f /app/config.yml ]; then
  echo "No config file found. Exiting..."
  exit
fi

if [ ! -d /app/data ]; then
  mkdir -p /app/data
fi

git -C /go/src/AutoDelete pull
cd /go/src/AutoDelete
go build -ldflags="-s -w" -v -o /app/autodelete /go/src/AutoDelete/cmd/autodelete
cd /app

/app/autodelete
